[package]
name = "xkcd_retriever"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
awc = { version = "3", features = ["rustls"] }
serde = { version = "1", features = [ "derive"] }